### ISSUE TITLE
Missing the file of outlier_detection_sd.py

### ISSUE THREAD

**Issue by Noval11** [rashadulrakib/short-text-clustering-enhancement#1]
Hi, Thank you for your work. It seems that you forgot to upload the file outlier_detection_sd.py. Can you upload it or send it to my email : wangqinglian1@gmail.com. Thanks!

**Comment by rashadulrakib** [comment]
Hello, I have added the file in github. I think, you do not need this file to run the system. Thanks for your interest in my work

**Comment by Noval11** [comment]
> Hello, I have added the file in github. I think, you do not need this file to run the system. Thanks for your interest in my work

Thanks a lot. You are right.
